[package]
name = "hx711"
version = "0.1.0"
authors = ["Jonas Hagen <jonas.hagen3@gmail.com>"]
edition = "2018"

[dependencies]
nb = "0.1.1"

[dependencies.embedded-hal]
version = "0.2.2"
features = ["unproven"]